# Generated by Django 5.2.6 on 2025-10-18 01:50

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BatteryCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='分类名称')),
                ('description', models.TextField(blank=True, max_length=200, verbose_name='分类描述')),
                ('icon', models.CharField(default='glyphicon-flash', max_length=50, verbose_name='图标')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '电池分类',
                'verbose_name_plural': '电池分类',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='BatteryType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='类型名称')),
                ('description', models.TextField(blank=True, max_length=200, verbose_name='类型描述')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='battery.batterycategory', verbose_name='所属分类')),
            ],
            options={
                'verbose_name': '电池类型',
                'verbose_name_plural': '电池类型',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Battery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='电池名称')),
                ('serial_number', models.CharField(max_length=50, unique=True, verbose_name='序列号')),
                ('status', models.CharField(choices=[('available', '可用'), ('rented', '已租出'), ('maintenance', '维护中'), ('retired', '已退役')], default='available', max_length=20, verbose_name='状态')),
                ('capacity', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='容量(Ah)')),
                ('voltage', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='电压(V)')),
                ('power', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='功率(W)')),
                ('weight', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='重量(kg)')),
                ('daily_rental_price', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='日租金(元)')),
                ('deposit', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='押金(元)')),
                ('location', models.CharField(max_length=100, verbose_name='存放位置')),
                ('latitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True, verbose_name='纬度')),
                ('longitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True, verbose_name='经度')),
                ('image', models.ImageField(default='battery_images/default.jpg', upload_to='battery_images/', verbose_name='电池图片')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('battery_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='battery.batterytype', verbose_name='电池类型')),
            ],
            options={
                'verbose_name': '电池信息',
                'verbose_name_plural': '电池信息',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BatteryUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(verbose_name='开始时间')),
                ('end_time', models.DateTimeField(blank=True, null=True, verbose_name='结束时间')),
                ('current_charge', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='当前电量(%)')),
                ('total_usage_hours', models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='总使用时长(小时)')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否正在使用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('battery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='battery.battery', verbose_name='电池')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '电池使用记录',
                'verbose_name_plural': '电池使用记录',
                'ordering': ['-start_time'],
            },
        ),
        migrations.CreateModel(
            name='RentalOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(max_length=20, unique=True, verbose_name='订单号')),
                ('start_date', models.DateTimeField(verbose_name='开始时间')),
                ('end_date', models.DateTimeField(verbose_name='结束时间')),
                ('rental_days', models.IntegerField(verbose_name='租赁天数')),
                ('daily_price', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='日租金')),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='总金额')),
                ('deposit_amount', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='押金')),
                ('status', models.CharField(choices=[('pending', '待确认'), ('confirmed', '已确认'), ('active', '使用中'), ('completed', '已完成'), ('cancelled', '已取消')], default='pending', max_length=20, verbose_name='订单状态')),
                ('notes', models.TextField(blank=True, max_length=500, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('battery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='battery.battery', verbose_name='电池')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '租赁订单',
                'verbose_name_plural': '租赁订单',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BatteryReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(choices=[(1, '1星'), (2, '2星'), (3, '3星'), (4, '4星'), (5, '5星')], verbose_name='评分')),
                ('comment', models.TextField(max_length=500, verbose_name='评价内容')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('battery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='battery.battery', verbose_name='电池')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '电池评价',
                'verbose_name_plural': '电池评价',
                'ordering': ['-created_at'],
                'unique_together': {('battery', 'user')},
            },
        ),
    ]
