# Generated by Django 5.2.6 on 2025-10-20 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('battery', '0002_batteryreview_updated_at_alter_batteryreview_battery_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='batteryusage',
            name='baseline_charge',
            field=models.IntegerField(default=100, verbose_name='基线电量(%)'),
        ),
        migrations.AddField(
            model_name='batteryusage',
            name='is_discharging',
            field=models.BooleanField(default=True, verbose_name='是否放电中'),
        ),
    ]
