# Generated by Django 5.2.6 on 2025-10-20 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('battery', '0003_batteryusage_baseline_charge_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='battery',
            name='image',
            field=models.ImageField(blank=True, default='', upload_to='battery_images/', verbose_name='电池图片'),
        ),
    ]
