"""
Django settings for New_energy_battery project.

Generated by 'django-admin startproject' using Django 5.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path

from captcha.conf.settings import CAPTCHA_NOISE_FUNCTIONS

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-f(qgc$bx@7hlunwm=&x6n+p_tsa+38=lwg5%*7-^@z=q=hzn4v'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'simpleui',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'user',
    'battery',
    'station',
    'captcha',

]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',

]

ROOT_URLCONF = 'New_energy_battery.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates']
        ,
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'New_energy_battery.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

# LANGUAGE_CODE = 'en-us'
#
# TIME_ZONE = 'UTC'

LANGUAGE_CODE = 'zh-hans'

TIME_ZONE = 'Asia/Shanghai'


USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field


# SMTP 发送邮件协议
# POP3/IMAP 接受邮件协议


# QQ 配置
# 邮件服务商
# EMAIL_HOST = "smtp.qq.com"
# 服务端口 QQ必须使用（SSL、TSL）
# EMAIL_USE_SSL = True
# EMAIL_PORT = 465

# 邮箱账户 和密码(授权码)
# EMAIL_HOST_USER = "3112201774@qq.com"
# EMAIL_HOST_PASSWORD = "uybczrfwmojvcbeg"
# DEFAULT_FROM_EMAIL = "3112201774@qq.com"



# 163配置
EMAIL_HOST = "smtp.163.com"
# 服务端口 没有使用（SSL、TSL）
EMAIL_PORT = 25
EMAIL_HOST_USER = "15138001200@163.com"
EMAIL_HOST_PASSWORD = "FXbBEgNVrRH6yJju"
DEFAULT_FROM_EMAIL = "15138001200@163.com"












DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
STATICFILES_DIRS = [BASE_DIR / 'static']
AUTH_USER_MODEL = "user.CustomUser"
MEDIA_ROOT = BASE_DIR / 'media'
MEDIA_URL = "media/"
CAPTCHA_FONT_SIZE = 16
# CAPTCHA_BACKGROUND_COLOR = 'red'
# CAPTCHA_FOREGROUND_COLOR = 'blue'
# CAPTCHA_CHALLENGE_FUNCT = "captcha.helpers.math_challenge"
CAPTCHA_IMAGE_SIZE = (100,50)

CAPTCHA_NOISE_FUNCTIONS = None

# 登录相关设置
LOGIN_URL = '/login/'  # 未登录用户访问需要登录的页面时重定向到这里
LOGIN_REDIRECT_URL = '/'  # 登录成功后默认重定向到首页
LOGOUT_REDIRECT_URL = '/login/'  # 退出登录后重定向到登录页