# Generated by Django 5.2.7 on 2025-10-15 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='describe',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
    ]
