# Generated by Django 5.2.6 on 2025-10-20 07:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('battery', '0002_batteryreview_updated_at_alter_batteryreview_battery_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BatteryStation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='网点名称')),
                ('address', models.CharField(max_length=200, verbose_name='详细地址')),
                ('phone', models.CharField(max_length=20, verbose_name='联系电话')),
                ('latitude', models.DecimalField(decimal_places=7, max_digits=10, verbose_name='纬度')),
                ('longitude', models.DecimalField(decimal_places=7, max_digits=10, verbose_name='经度')),
                ('description', models.TextField(blank=True, max_length=500, verbose_name='网点描述')),
                ('business_hours', models.CharField(default='09:00-21:00', max_length=50, verbose_name='营业时间')),
                ('max_batteries', models.IntegerField(default=100, verbose_name='最大存放电池数')),
                ('current_batteries', models.IntegerField(default=0, verbose_name='当前存放电池数')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否营业')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '电池网点',
                'verbose_name_plural': '电池网点',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='StationRental',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rental_date', models.DateTimeField(verbose_name='租赁时间')),
                ('expected_return_date', models.DateTimeField(verbose_name='预期归还时间')),
                ('actual_return_date', models.DateTimeField(blank=True, null=True, verbose_name='实际归还时间')),
                ('rental_amount', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='租赁金额')),
                ('status', models.CharField(choices=[('pending', '待确认'), ('confirmed', '已确认'), ('completed', '已完成'), ('cancelled', '已取消')], default='pending', max_length=20, verbose_name='状态')),
                ('notes', models.TextField(blank=True, max_length=500, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('battery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='battery.battery', verbose_name='电池')),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rentals', to='station.batterystation', verbose_name='网点')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='station_rentals', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '网点租赁记录',
                'verbose_name_plural': '网点租赁记录',
                'ordering': ['-rental_date'],
            },
        ),
        migrations.CreateModel(
            name='StationReturn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('return_date', models.DateTimeField(auto_now_add=True, verbose_name='归还时间')),
                ('battery_condition', models.CharField(choices=[('excellent', '完好'), ('good', '良好'), ('fair', '一般'), ('poor', '有损坏')], default='good', max_length=20, verbose_name='电池状态')),
                ('extra_fee', models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='额外费用')),
                ('refund_amount', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='退款金额')),
                ('notes', models.TextField(blank=True, max_length=500, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('rental', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='return_record', to='station.stationrental', verbose_name='租赁记录')),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='returns', to='station.batterystation', verbose_name='归还网点')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '网点归还记录',
                'verbose_name_plural': '网点归还记录',
                'ordering': ['-return_date'],
            },
        ),
    ]
